# Generated by Django 4.1.7 on 2023-05-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_alter_products_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddresses',
            name='status',
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
