# Generated by Django 4.1.7 on 2023-05-07 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_remove_useraddresses_status_alter_categories_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('canceled', 'canceled'), ('completed', 'completed'), ('created', 'created'), ('in_basket', 'in_basket')], max_length=10),
        ),
    ]
